### ISSUE TITLE
作者大大，请问如何把包导出

### ISSUE THREAD

**Issue by picetor** [Dclef/WebViewApp#2]
如题，菜鸡求问

**Comment by Dclef** [comment]
![ef174e10513add830bd090011e6f115a_720](https://github.com/Dclef/WebViewApp/assets/42974381/ebe61c31-c1f2-43cb-a42f-87f0037450a5)

**Comment by picetor** [comment]
只是不知道，导出的APK在哪里，还是打包前的文件在哪里。说起算卦，我的六爻很差，八字还可以勉强。
